name: Debug pnpm

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  debug-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8 # Specify a known pnpm version

      - name: Check pnpm version
        run: pnpm --version

      - name: Print PATH
        run: echo $PATH

  publish-package:
    name: Publish Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: pnpm install # or npm install or yarn install
      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
